### ISSUE TITLE
Invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by LILILIhuahuahua** [LILILIhuahuahua/ustc_tencent_game#5]
## Env
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/randy/Library/Caches/go-build"
GOENV="/Users/randy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/randy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/randy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/randy/go/src/github.com/LILILIhuahuahua/ustc_tencent_game-for-dgs/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vm/5gsvclcx6z787y6r6chf9tp40000gn/T/go-build2849468285=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## Version
branch: dgs
commit hash:  d6584b2e124b737bf72e39ad3f59d951140816d4

## Problem
Program will panic after running [TestGlobalPropInfoNotify](https://github.com/LILILIhuahuahua/ustc_tencent_game/blob/d6584b2e124b737bf72e39ad3f59d951140816d4/framework/test/client_test.go#L136) for a few seconds, panic info as follows:
```go
2021/03/08 10:05:28 unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x12feba3]

goroutine 22 [running]:
github.com/LILILIhuahuahua/ustc_tencent_game/framework/test.receive(0xc000113520)
	/Users/randy/go/src/github.com/LILILIhuahuahua/ustc_tencent_game/framework/test/client_test.go:126 +0x1d3
created by github.com/LILILIhuahuahua/ustc_tencent_game/framework/test.TestGlobalPropInfoNotify
	/Users/randy/go/src/github.com/LILILIhuahuahua/ustc_tencent_game/framework/test/client_test.go:164 +0x317
```

**Comment by LILILIhuahuahua** [comment]
Resolved
